[project]
name = "aprendihoje"
version = "0"
description = "Blog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
]

[dependency-groups]
dev = [
]

[build-system]
requires = ["uv_build>=0.8.6,<0.9.0"]
build-backend = "uv_build"
